store: /tmp/gidek/store
token: gho_hebelehubele
token_file: /var/run/secrets/github_token
repos:
  - type: single
    name: vst/gidek
  - type: user
    name: vst
  - type: organization
    name: fourmolu
