name: "Check Codebase"

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Codebase"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        uses: "DeterminateSystems/nix-installer-action@v16"

      - name: "Check Codebase"
        run: |
          nix develop --command hpack
          nix develop --command cabal update --ignore-project
          nix develop --command dev-test-build -c
