name: "Release"

on:
  push:
    branches:
      - "main"

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  release-please:
    runs-on: "ubuntu-latest"

    steps:
      - id: "release"
        name: "Release"
        uses: "googleapis/release-please-action@v4"

      - name: "Checkout Codebase"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Install nix"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "DeterminateSystems/nix-installer-action@v16"

      - name: "Check Application"
        if: "${{ steps.release.outputs.release_created }}"
        run: |
          nix develop --command hpack
          nix develop --command cabal update --ignore-project
          nix develop --command dev-build-static

      - name: "Upload Release Artifact"
        if: "${{ steps.release.outputs.release_created }}"
        run: |
          gh release upload "${{ steps.release.outputs.tag_name }}" /tmp/gidek-static-linux-x86_64
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
